### ISSUE TITLE
Question: Does this allow me to view the pictures of my cards as well?

### ISSUE THREAD

**Issue by aktcg** [Vassa94/KarutaCardsManager#1]
I was wondering if this is an interactive data chart or does it show the images of the cards so I can sort through?
Would you be able to upload a few screenshots as an example?

Thank you

**Comment by Vassa94** [comment]
> I was wondering if this is an interactive data chart or does it show the images of the cards so I can sort through? Would you be able to upload a few screenshots as an example?
> 
> Thank you

No, it does not have an image view. As each view is specific to the Bot, it would need to get them from its server and at the moment, I have not found any possible way. This tool only uses the csv sheet that the bot itself provides when using the k!sheet command.
Anyway, I'm still looking at options and wanting to improve it, so if I manage to do it, it will remain in the repo.

This is a current view of the app;
![2024-09-18 09_29_29-Karuta Cards manager - Opera](https://github.com/user-attachments/assets/c0078bf6-ffdb-45f5-a7b7-3e26a9bb8120)
